version: "3.9"

services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/minio
    command: server --console-address ":9090" /minio
    ports:
      - 9090:9090
      - 9000:9000
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
  minio-data:
    driver: local