server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/test-realm
      client:
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: test-rest-api
            client-secret: wCFIVaCdqV8QJLqDs3P9b3g6IiZorjsh
            scope: openid

#logging:
#  level:
#    org.springframework.security: TRACE