spring:
  application:
    name: Kotlin-CRUD-App
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${POSTGRES_SCHEMA}

server:
  port: 8086
