server:
  port: 8386

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: "localhost:29092"
    consumer:
      bootstrap-servers: "localhost:29092"
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-group-id
      properties:
        spring.json.trusted.packages: ru.kafka.simple.model

topics: test-topic