server:
  port: 8386

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: "http://localhost:8081"

    consumer:
      group-id: test-group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: ru.kafka.simple.model
        schema.registry.url: "http://localhost:8081"
        specific.avro.reader: "true"

topics: test-topic